### ISSUE TITLE
Remove redundant libraries from the compiled jar

### ISSUE THREAD

**Issue by StevenNL2000** [Commodore64x/VerifyMe#1]
TotalFreedomMod is a dependency, and that plugin already comes with a bunch of libraries, so including Aero and Lombok in this jar file too is a waste of space.

**Comment by Commodore64x** [comment]
But it will not compile if Aero is not listed as a dependency? Also Aero and lombok are very small, the bulk of the size of the jar is selenium.

**Comment by StevenNL2000** [comment]
@Commodore64x I'm not asking you to remove it from the dependencies, but from the jar file. The entirety of Spigot isn't in it either.

**Comment by Commodore64x** [comment]
@StevenNL2000 They should be already excluded from the jar? I'll check.

**Comment by StevenNL2000** [comment]
@Commodore64x My apologies, Lombok isn't included in the jar. Aero is, though.

**Comment by Commodore64x** [comment]
@StevenNL2000 I'll remove all plugins from the jar

**Comment by Commodore64x** [comment]
The smallest size I can get it down to is 20.0 MB that will have to do.

**Comment by Commodore64x** [comment]
@StevenNL2000 confirm this is fixed?

**Comment by StevenNL2000** [comment]
@Commodore64x If should be fine if your latest commit compiles properly. I don't have an environment set up for that at the moment.
