### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by GX2H912** [Commodore64x/VerifyMe#2]
https://github.com/Commodore64x/VerifyMe/blob/master/src/main/java/com/commodore/verifyme/command/Command_forum.java

From lines 56 - 59

"authorised" --> "authorized"

**Comment by Focusvity** [comment]
Actually, it’s not incorrect. American English is different to British English.

**Comment by Commodore64x** [comment]
I've fixed up the spelling, thanks for bringing this up.
